### ISSUE TITLE
New workshop modules

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk-rfcs#10]
|PR|Champion|
|--|--------|
|# |        |

## Description

- [ ] Containers
- [ ] CI/CD (when available)

## Progress

- [x] Tracking Issue Created
- [ ] RFC PR Created 
- [ ] Core Team Member Assigned 
- [ ] Initial Approval / Final Comment Period
- [ ] Ready For Implementation
    
    - [ ] implementation issue 1
- [ ] Resolved

**Comment by pgollucci** [comment]
I would love to be involved here.

**Comment by mrgrain** [comment]
Doesn't fit our definition of an RFC anymore (this is just a work item)

Marking this RFCs as `stale` since there has been little recent activity and it is not currently close to getting accepted as-is. We appreciate the effort that has gone into this proposal. Marking an RFCs as stale is not a one-way door. If you have made substantial changes to the proposal, please open a new issue/RFC. You might also consider raising a PR to [aws/aws-cdk](https://github.com/aws/aws-cdk/) directly or self-publishing to Construct Hub.
