### ISSUE TITLE
Improvements to Reference docs

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk-rfcs#13]
|PR|Champion|
|--|--------|
|# |        |

## Description

- [ ] Open source multi-language doc renderer (jsii?)
- [ ] Add the single universal experience support all languages
- [ ] Consider whether we still want the idiomatic references
- [ ] SEO
- [ ] Overall stability matrix
- [ ] Remove per-module stability and only show per-construct stability (suggested by @rhboyd)
- [ ] Google juice is pretty bad right now. All languages in one AWSDocs-like template, better crosslinking, better search (@rix0rrr)

## Progress

- [x] Tracking Issue Created
- [ ] RFC PR Created 
- [ ] Core Team Member Assigned 
- [ ] Initial Approval / Final Comment Period
- [ ] Ready For Implementation
    
    - [ ] implementation issue 1
- [ ] Resolved

**Comment by mrgrain** [comment]
While docs still need improvements, this issue predates the current docs.

Marking this RFCs as `stale` since there has been little recent activity and it is not currently close to getting accepted as-is. We appreciate the effort that has gone into this proposal. Marking an RFCs as stale is not a one-way door. If you have made substantial changes to the proposal, please open a new issue/RFC. You might also consider raising a PR to [aws/aws-cdk](https://github.com/aws/aws-cdk/) directly or self-publishing to Construct Hub.
