### ISSUE TITLE
"fromLookup" for additional resources

### ISSUE THREAD

**Issue by thibaut-pro** [aws/aws-cdk-rfcs#139]
This is a request for AWS CDK to support selectors (a la jQuery/CSS) for resources that would enable me to import existing resources by type and tag.

### Use Case

I would like to reference existing resources (https://docs.aws.amazon.com/cdk/latest/guide/resources.html) but I don't necessarily know the resource ARN. VPCs support lookups already but I would like to see that expanded to other AWS constructs.

### Proposed Solution

This was mentioned in https://github.com/aws/aws-cdk/issues/1136#issuecomment-450351511 which could be a starting point to implement generalized selectors.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by mrgrain** [comment]
Marking this RFCs as `stale` since there has been little recent activity and it is not currently close to getting accepted as-is. We appreciate the effort that has gone into this proposal. Marking an RFCs as stale is not a one-way door. If you have made substantial changes to the proposal, please open a new issue/RFC. You might also consider raising a PR to [aws/aws-cdk](https://github.com/aws/aws-cdk/) directly or self-publishing to Construct Hub.
