### ISSUE TITLE
Introspection API

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk-rfcs#19]
|PR|Champion|
|--|--------|
|# |        |

## Description

Allow read only inspection of resolved configuration properties in all L2s:

```ts
const queue = new sqs.Queue(this, 'MyQueue');
assert queue.visibilityTimeout === Duration.seconds(30)
```

See https://github.com/aws/aws-cdk/issues/6560

## Progress

- [x] Tracking Issue Created
- [ ] RFC PR Created 
- [ ] Core Team Member Assigned 
- [ ] Initial Approval / Final Comment Period
- [ ] Ready For Implementation
    
    - [ ] implementation issue 1
- [ ] Resolved

**Comment by mrgrain** [comment]
Marking this RFCs as `stale` since there has been little recent activity and it is not currently close to getting accepted as-is. We appreciate the effort that has gone into this proposal. Marking an RFCs as stale is not a one-way door. If you have made substantial changes to the proposal, please open a new issue/RFC. You might also consider raising a PR to [aws/aws-cdk](https://github.com/aws/aws-cdk/) directly or self-publishing to Construct Hub.
