### ISSUE TITLE
Construct scope relocation

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk-rfcs#201]
|PR|Champion|
|--|--------|
|# |    @RomainMuller     |

## Description

To allow preserving paths and generated identities when refactoring construct trees, we propose to introduce `construct.node.relocate(path)` which will allow specifying the root path for a scope and all its children.

For example, if I have a set of stacks in production which I want to bundle into a new `Stage` type so that I can deploy them through CDK Pipelines and deploy them without replacement of resources, I would use `relocate()` to ensure that all paths and unique IDs are preserved as I refactor my code.

## Progress

- [x] Tracking Issue Created
- [ ] RFC PR Created 
- [ ] Core Team Member Assigned 
- [ ] Initial Approval / Final Comment Period
- [ ] Ready For Implementation
    
    - [ ] implementation issue 1
- [ ] Resolved

**Comment by mrgrain** [comment]
Marking this RFCs as `stale` since there has been little recent activity and it is not currently close to getting accepted as-is. We appreciate the effort that has gone into this proposal. Marking an RFCs as stale is not a one-way door. If you have made substantial changes to the proposal, please open a new issue/RFC. You might also consider raising a PR to [aws/aws-cdk](https://github.com/aws/aws-cdk/) directly or self-publishing to Construct Hub.
