### ISSUE TITLE
Construct library pattern for metrics

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk-rfcs#229]
- [ ] Productize metric code generation
   - [ ] Move the source model to L2 (from cfnspec)
   - [ ] Consider Smithy as a source format for the model
   - [ ] support static "all" metrics and update guidelines
- [ ] Add `metric` to `cdk.IResource`
- [ ] Implement and apply rule **`awslint:metrics-on-interface`**: All metric methods should be on the construct interface and not the class
- [ ] Implement and apply rule **`awslint:metrics-generic-method`**: All constructs which emit metrics should have at least a single generic "metric" method
- [ ] Implement and apply rule **`awslint:metrics-method-signature`**: Metric method signature should adhere to the rules
- [ ] Implement and apply rule **`awslint:metrics-static-all-generic`**: If there is a static all metric method, it should at least include a single "metricAll" generic method
- [ ] Implement and apply rule **`awslint:metrics-static-all`**: Verify signature of all "metricAllXxx" static methods

**Comment by mrgrain** [comment]
Marking this RFCs as `stale` since there has been little recent activity and it is not currently close to getting accepted as-is. We appreciate the effort that has gone into this proposal. Marking an RFCs as stale is not a one-way door. If you have made substantial changes to the proposal, please open a new issue/RFC. You might also consider raising a PR to [aws/aws-cdk](https://github.com/aws/aws-cdk/) directly or self-publishing to Construct Hub.
