### ISSUE TITLE
Stateful resource support

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk-rfcs#23]
|PR|Champion|
|--|--------|
|# |        |

## Description

- [ ] Identifying L2s as stateful resource
- [ ] Default removal policy
- [ ] Automatic stack policy for protecting resources
- [ ] Related to traffic shifting
- [ ] Related to imports

## Progress

- [x] Tracking Issue Created
- [ ] RFC PR Created 
- [ ] Core Team Member Assigned 
- [ ] Initial Approval / Final Comment Period
- [ ] Ready For Implementation
    
    - [ ] implementation issue 1
- [ ] Resolved

**Comment by eladb** [comment]
From #76:

- [ ] Add `stateful: boolean` to `cdk.IResource`
- [ ] Refactor RemovalPolicy to an enum-like and move `apply` to there
- [ ] Consider how/if we should model statefulness in L1 considering aws/aws-cdk-rfcs#73 
- [ ] Implement and apply rule **`awslint:state-annotation`**: All resource classes should be marked with "@stateful" or "@stateless"
- [ ] Implement and apply rule **`awslint:state-removal-policy-prop`**: All stateful resource should have a "removalPolicy" prop
- [ ] Implement and apply rule **`awslint:state-stateful-property`**: All resources should have a "stateful" property returns true/false

**Comment by mrgrain** [comment]
Already exists in a basic form. Unclear what more is proposed.

Marking this RFCs as `stale` since there has been little recent activity and it is not currently close to getting accepted as-is. We appreciate the effort that has gone into this proposal. Marking an RFCs as stale is not a one-way door. If you have made substantial changes to the proposal, please open a new issue/RFC. You might also consider raising a PR to [aws/aws-cdk](https://github.com/aws/aws-cdk/) directly or self-publishing to Construct Hub.
