### ISSUE TITLE
Construct library pattern for grants

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk-rfcs#230]
- [ ] Update guidelines with details on how to use the Grant API
- [ ] Add "grant" to `cdk.IResource`
- [ ] Implement and apply rule **`awslint:grants-on-interface`**: Grant methods should be on the construct interface, not the class
- [ ] Implement and apply rule **`awslint:grants-grant-method`**: All constructs should have at least a single "grant" method with the defined signature
- [ ] Implement and apply rule **`awslint:grants-signature`**: Grant methods should adhere to signature rules
- [ ] Implement and apply rule **`awslint:grants-static-all`**: Static grant methods should be on the class and adhere to the signature and naming conventions

**Comment by mrgrain** [comment]
Marking this RFCs as `stale` since there has been little recent activity and it is not currently close to getting accepted as-is. We appreciate the effort that has gone into this proposal. Marking an RFCs as stale is not a one-way door. If you have made substantial changes to the proposal, please open a new issue/RFC. You might also consider raising a PR to [aws/aws-cdk](https://github.com/aws/aws-cdk/) directly or self-publishing to Construct Hub.
