### ISSUE TITLE
Construct library pattern for resources that use a VPC

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk-rfcs#231]
- [ ] Implement and apply rule **`awslint:vpc-props`**: If a CloudFormation resource has VPC-related properties, the construct props should have "vpc" and "vpcSubnets"

**Comment by mrgrain** [comment]
Marking this RFCs as `stale` since there has been little recent activity and it is not currently close to getting accepted as-is. We appreciate the effort that has gone into this proposal. Marking an RFCs as stale is not a one-way door. If you have made substantial changes to the proposal, please open a new issue/RFC. You might also consider raising a PR to [aws/aws-cdk](https://github.com/aws/aws-cdk/) directly or self-publishing to Construct Hub.
