### ISSUE TITLE
Construct library pattern for resources that need IAM roles

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk-rfcs#232]
- [ ] Implement and apply rule **`awslint:role-config-prop`**: If the CloudFormation resource has a "Role" property the construct must have an optional "role: IRole" prop
- [ ] Implement and apply rule **`awslint:role-property`**: Constructs with a role should have a "readonly role: IRole" property on their construct interface
- [ ] Implement and apply rule **`awslint:role-add-to-policy`**: Constructs with a role must have an "addToRolePolicy" method on the construct interface
- [ ] Implement and apply rule **`awslint:resource-policy-prop`**: The "resourcePolicy" prop should be optional and accept an array of PolicyStatements
- [ ] Implement and apply rule **`awslint:resource-policy-add-to-policy`**: Constructs that have a resource policy should have an addToResourcePolicy method on their interface

**Comment by mrgrain** [comment]
Marking this RFCs as `stale` since there has been little recent activity and it is not currently close to getting accepted as-is. We appreciate the effort that has gone into this proposal. Marking an RFCs as stale is not a one-way door. If you have made substantial changes to the proposal, please open a new issue/RFC. You might also consider raising a PR to [aws/aws-cdk](https://github.com/aws/aws-cdk/) directly or self-publishing to Construct Hub.
