### ISSUE TITLE
CDK Common Stored Data Type Model

### ISSUE THREAD

**Issue by MrArnoldPalmer** [aws/aws-cdk-rfcs#247]
|PR|Champion|
|--|--------|
|# |        |

## Description

While defining the CDK constructs for AppSync, it has become apparent that defining the "shape" of data that aws services interact with occurs in multiple places within CDK. Often times, it is useful for these services to be able to pass around and reference the type of data stored in another service.

If a user declares a type "Person", and that type is stored in a dynamo table, as well as is in the message body of an SQS queue, and declared within a graphql schema, a common data model would allow CDK to more intelligently construct references between the resources.

This is very similar to what [Punchcard is doing](https://github.com/punchcard/punchcard/blob/master/examples/lib/graphql.ts). There is a common set of primitives like `Type` that can be extended. You can declare a dynamo db table with an instance of `Type` as well as a graphql type.

This obviously could be useful in a ton of services where data flows in/out with a known shape:
DynamoDB
RDS
SNS/SQS/Kinesis
ApiGateway
AppSync
StepFunctions

## Progress

- [x] Tracking Issue Created
- [ ] RFC PR Created 
- [ ] Core Team Member Assigned 
- [ ] Initial Approval / Final Comment Period
- [ ] Ready For Implementation
    
    - [ ] implementation issue 1
- [ ] Resolved

**Comment by mrgrain** [comment]
Marking this RFCs as `stale` since there has been little recent activity and it is not currently close to getting accepted as-is. We appreciate the effort that has gone into this proposal. Marking an RFCs as stale is not a one-way door. If you have made substantial changes to the proposal, please open a new issue/RFC. You might also consider raising a PR to [aws/aws-cdk](https://github.com/aws/aws-cdk/) directly or self-publishing to Construct Hub.
