### ISSUE TITLE
Standardized context key for "cheap mode"

### ISSUE THREAD

**Issue by rix0rrr** [aws/aws-cdk-rfcs#248]
|PR|Champion|
|--|--------|
|# |        |

## Description

It would be good if we had a standardized context key for "cheap mode" deployments, which people could set on development mode stacks.

If set, the presence of the key would control:

* Smaller default instance sizes
* Lower default replication factors
* Use default KMS key instead of custom one
* VPS with only public subnets by default
* ...etc...

The advantage of having a single well-established key for this would be *semantics*: the alternative is ad-hoc keys established on a per-module basis, for the same functionality.

Not all modules have to support it, but the ones that do should trigger off the same key. 

Support for this key in various modules can be added piecemeal via PRs and can be community-contributed.

## Progress

- [x] Tracking Issue Created
- [ ] RFC PR Created 
- [ ] Core Team Member Assigned 
- [ ] Initial Approval / Final Comment Period
- [ ] Ready For Implementation
    
    - [ ] implementation issue 1
- [ ] Resolved

**Comment by mrgrain** [comment]
Marking this RFCs as `stale` since there has been little recent activity and it is not currently close to getting accepted as-is. We appreciate the effort that has gone into this proposal. Marking an RFCs as stale is not a one-way door. If you have made substantial changes to the proposal, please open a new issue/RFC. You might also consider raising a PR to [aws/aws-cdk](https://github.com/aws/aws-cdk/) directly or self-publishing to Construct Hub.
