### ISSUE TITLE
200 resource limit tools & guidance

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk-rfcs#27]
|PR|Champion|
|--|--------|
|# |        |

## Description

- [ ] Blog post
- [ ] Warn when you reach 150

## Progress

- [x] Tracking Issue Created
- [ ] RFC PR Created 
- [ ] Core Team Member Assigned 
- [ ] Initial Approval / Final Comment Period
- [ ] Ready For Implementation
    
    - [ ] implementation issue 1
- [ ] Resolved

**Comment by mrgrain** [comment]
Marking this RFCs as `stale` since there has been little recent activity and it is not currently close to getting accepted as-is. We appreciate the effort that has gone into this proposal. Marking an RFCs as stale is not a one-way door. If you have made substantial changes to the proposal, please open a new issue/RFC. You might also consider raising a PR to [aws/aws-cdk](https://github.com/aws/aws-cdk/) directly or self-publishing to Construct Hub.

**Comment by awsmjs** [comment]
Closing this ticket. We don't have the bandwidth to collaborate on design or implementation. We suggest experimentation for this feature first via a separate package or a fork if needed. If a successful implementation emerges, reopen the proposal with details on the functionality and how it can be implemented in the core library.
