### ISSUE TITLE
Add L2 constructs for Amazon FSx Windows

### ISSUE THREAD

**Issue by Bermpje** [aws/aws-cdk-rfcs#467]
## Description

In CDK there are only L2 constructs available for Amazon FSx Lustre. This RFC is to add the Amazon FSx Windows L2 constructs to the existing @aws-cdk/aws-fsx package.

The aim of this addition to the library is to provide an even easier way of defining a FSx Windows filesystem by providing constructs with more guard rails and contextual information to get users going straight away.

## Roles

| Role                | User
|---------------------|------------------------------
| Proposed by         | @bermpje
| Author(s)           | @bermpje
| API Bar Raiser      | @rix0rrr 
| Stakeholders        | @alia

> See [RFC Process](https://github.com/aws/aws-cdk-rfcs#rfc-process) for details

## Workflow

- [x] Tracking issue created (label: `status/proposed`)
- [x] API bar raiser assigned (ping us at [#aws-cdk-rfcs](https://cdk-dev.slack.com/archives/C025ZFGMUCD) if needed)
- [ ] Kick off meeting
- [ ] RFC pull request submitted (label: `status/review`)
- [ ] Community reach out (via Slack and/or Twitter)
- [ ] API signed-off (label `api-approved` applied to pull request)
- [ ] Final comments period (label: `status/final-comments-period`)
- [ ] Approved and merged (label: `status/approved`)
- [ ] Execution plan submitted (label: `status/planning`)
- [ ] Plan approved and merged (label: `status/implementing`)
- [ ] Implementation complete (label: `status/done`)

---

> Author is responsible to progress the RFC according to this checklist, and
apply the relevant labels to this issue so that the RFC table in README gets
updated.

**Comment by mrgrain** [comment]
Marking this RFCs as `stale` since there has been little recent activity and it is not currently close to getting accepted as-is. We appreciate the effort that has gone into this proposal. Marking an RFCs as stale is not a one-way door. If you have made substantial changes to the proposal, please open a new issue/RFC. You might also consider raising a PR to [aws/aws-cdk](https://github.com/aws/aws-cdk/) directly or self-publishing to Construct Hub.
