### ISSUE TITLE
Standardize security groups

### ISSUE THREAD

**Issue by rix0rrr** [aws/aws-cdk-rfcs#51]
|PR|Champion|
|--|--------|
|# |        |

## Description

The behavior right now is haphazard and not well thought-out. Needs to be standardized.

- Provided SGs vs. created SGs: people seem to be expecting that provided SGs are treated as immutable.
- One SG vs multiple SGs: it does not make sense to mutate all SGs in a connections object, 1 would have been enough.
- Should we add a mutable flag, just like for roles?

## Progress

- [x] Tracking Issue Created
- [ ] RFC PR Created 
- [ ] Core Team Member Assigned 
- [ ] Initial Approval / Final Comment Period
- [ ] Ready For Implementation
    
    - [ ] implementation issue 1
- [ ] Resolved

**Comment by mrgrain** [comment]
Marking this RFCs as `stale` since there has been little recent activity and it is not currently close to getting accepted as-is. We appreciate the effort that has gone into this proposal. Marking an RFCs as stale is not a one-way door. If you have made substantial changes to the proposal, please open a new issue/RFC. You might also consider raising a PR to [aws/aws-cdk](https://github.com/aws/aws-cdk/) directly or self-publishing to Construct Hub.
