### ISSUE TITLE
One-off "job" Stacks ("auto destruct")

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk-rfcs#69]
We should consider some support for "one off" stacks. This can be used for various things like running integration tests or setting up infra for a big data analysis job that requires many resources and then should automatically tear down.

I would implement this is an construct that you can add to a stack and will automatically delete it when it receives an SNS notification. Then, when the job is over, it can publish the notification and the "auto destruct" logic will issue a `DeleteStack`.

**Comment by pgollucci** [comment]
https://github.com/jmb12686/cdk-time-bomb is this

**Comment by mrgrain** [comment]
Solved by Ecosystem.

Marking this RFCs as `stale` since there has been little recent activity and it is not currently close to getting accepted as-is. We appreciate the effort that has gone into this proposal. Marking an RFCs as stale is not a one-way door. If you have made substantial changes to the proposal, please open a new issue/RFC. You might also consider raising a PR to [aws/aws-cdk](https://github.com/aws/aws-cdk/) directly or self-publishing to Construct Hub.
