### ISSUE TITLE
Cost Estimation Tools

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk-rfcs#70]
Some ideas around cost estimation:

1. Calculate fixed cost based on a CloudFormation template ([aws cloudformation estimate-template-cost](https://docs.aws.amazon.com/cli/latest/reference/cloudformation/estimate-template-cost.html))
2. Auto-tag all resources in a construct/stack and use the pricing APIs to track variable cost as well, so users can add constructs that alarm if costs has gone too high or even auto-destroy?)

**Comment by gabrielenosso** [comment]
Just wanted to mention that in the https://github.com/aws/aws-cdk-rfcs there are 2 proposal for a Cost Estimation Tool / Cost Calculator.

Numbers 70 (this one) and 22.

**Comment by master-harvey** [comment]
We can tag all taggable resources in a stack using the tags prop in the Stack object constructor. You can then go to Cost Explorer in the console and filter by tag to track actual usage costs.

I haven't tried this yet but it looks like the CloudFormation CLI already has a way to get an estimate ahead of time: 
https://docs.aws.amazon.com/cli/latest/reference/cloudformation/estimate-template-cost.html

**Comment by blade2005** [comment]
So something like 
```bash
find cdk.out -name '*.template.json' | while read file;do aws cloudformation estimate-template-cost --template-body file://$file --output text --query Url;done
``` 
should work but it doesn't in part because of
> An error occurred (ValidationError) when calling the EstimateTemplateCost operation: Resource Type AWS::CDK::Metadata (Logical ID: CDKMetadata) does not belong to resourceCostCalculator map.

or large files were now you gotta upload it to just to estimate it.

Ultimately the cost estimate api doesn't support `AWS::CDK::Metadata` objects which is where this is failing.

**Comment by spoco2** [comment]
We're using CDK, we have a number of stacks we deploy, we're at early stages of our start up and only have testing data loads through the system so far.

Manually trying to work out the cost of this system as we scale load is _hugely difficult_ and massively time consuming due to the multitude of ways that each part of the system has different cost models applied by AWS, and different pricing breakpoints based on usage volumes.

So, being able to point a tool at a CDK stack (or collection of stacks more realistically) and then have access to sliders/inputs to alter the volume through the system/time used etc. and get projected costs out would be _massively useful_.

5 years on since this was opened and other issues rolled into it, and still no viable tool is very disappointing. 

"Go and use Cost Explorer in the console, it has forecasting" is a useless thing that gets said a lot around the traps, as that assumes you already have a system that has had production loads running against it, and then all it'll do is assume some growth against that.

Gives no ability to change volumes, usage, anything.

This all makes it _very_ hard to estimate the cost of AWS expenditure for startups.

**Comment by ahammond** [comment]
We are looking for a way to put an estimated cost delta into our PRs. My take on this is that it might possibly be part of Cfn, but is almost certainly not part of CDK. If it's not part of Cfn, then it's probably some external integration which would be managed for PRs by projen.

**Comment by awsmjs** [comment]
Closing this ticket. We don't have the bandwidth to collaborate on design or implementation. We suggest experimentation for this feature first via a separate package or a fork if needed. If a successful implementation emerges, reopen the proposal with details on the functionality and how it can be implemented in the core library.

**Comment by ahammond** [comment]
Fair enough. Can you suggest who we should be talking to about this?

**Comment by glenngillen** [comment]
Stumbled across this looking for my own loose ends of github issues to reply to, and didn't realise there was an RFC about it. If you're still looking for cfn and/or cdk cost estimates they're both possible in the latest `infracost` CLI.
