### ISSUE TITLE
Project Structure Guidelines

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk-rfcs#8]
|PR|Champion|
|--|--------|
|# |        |

## Description

- [ ] Blog about how to organize projects
- [ ] Variability between environments/stacks
- [ ] Secrets/account IDs
- [ ] CFN parameters - yes/no?
- [ ] 200 resource limits (https://github.com/awslabs/aws-cdk-rfcs/issues/27)
- [ ] Publish article to [Builder's Library](https://aws.amazon.com/builders-library/?cards-body.sort-by=item.additionalFields.customSort&cards-body.sort-order=asc)

## Progress

- [x] Tracking Issue Created
- [ ] RFC PR Created 
- [ ] Core Team Member Assigned 
- [ ] Initial Approval / Final Comment Period
- [ ] Ready For Implementation
    
    - [ ] implementation issue 1
- [ ] Resolved

**Comment by eladb** [comment]
Duplicate #66

**Comment by eladb** [comment]
@ericzbeard and @rix0rrr are working on a proposal

**Comment by mnoumanshahzad** [comment]
Probably the number of deployed stack limit reference needs to be modified, as the new default is `2000`.

Reference: https://aws.amazon.com/about-aws/whats-new/2021/06/aws-cloudformation-now-supports-more-stacks-per-aws-account/

**Comment by alexpulver** [comment]
@eladb adding reference to the [Recommended AWS CDK project structure for Python applications](https://aws.amazon.com/blogs/developer/recommended-aws-cdk-project-structure-for-python-applications/) blog post. Do you think it can tick the first checkbox? Should we make such a checkbox for each supported language due to variability in directory layouts?

Don't the [Environments](https://docs.aws.amazon.com/cdk/latest/guide/environments.html) and [Stacks](https://docs.aws.amazon.com/cdk/latest/guide/stacks.html) documentation cover the "Variability between environments/stacks"?

**Comment by mrgrain** [comment]
It's been a while but I think in general we have a lot of guidance around this now. Calling it a day. For concrete proposals please open a new PR/issue/RFC.
