### ISSUE TITLE
Weak references

### ISSUE THREAD

**Issue by jogold** [aws/aws-cdk-rfcs#82]
### Description

For some CloudFormation resources an [update sometimes requires a replacement](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html).

Examples of such resources are `AWS::RDS::DBInstance`, `AWS::DynamoDB::Table` or `AWS::Lambda::LayerVersion`.

Using those resources in a cross-stack fashion results in `Fn::ImportValue`s that will prevent those updates (lock situation).

The CDK could offer a way to loosely couple stacks by wrapping values in a SSM parameter in the producing stack and unwrapping it in the consuming stack.

### Proposed Solution

Add support for "weak references" which materialize through SSM parameters instead of CloudFormation exports/imports.

Things to consider:

- If an SSM parameter changes, all referencing stacks will need to be _manually_ updated in order to consume the new value. The desired behavior in the CDK is that this will automatically happen in `cdk deploy` and through CI/CD. One way to achieve this is to somehow "salt" the reference name so that the SSM parameter will be immutable and a new parameter will be created every time the value changes. This will invalidate the consuming stack since the SSM parameter name will be different.

### Prototype

Create a `Wrapper` class:
```ts
export class Wrapper extends cdk.Construct {
  private readonly parameterName: string;

  constructor(scope: cdk.Construct, id: string, value: string) {
    super(scope, id);

    this.parameterName = `/cdk/${this.node.uniqueId}`;

    new ssm.StringParameter(this, 'Parameter', {
      parameterName: this.parameterName,
      stringValue: value
    });
  }

  // To be used in the consuming stack
  // (will create a `Parameter` of type `AWS::SSM::Parameter::Value<String>`)
  public getValue(scope: cdk.Construct): string {
    scope.node.addDependency(this); // Force stacks dependency as no `Fn::ImportValue` will be generated
    return ssm.StringParameter.valueForStringParameter(scope, this.parameterName);
  }
}
```

Usage:
```ts
class StackA extends cdk.Stack {
  public readonly wrappedEndpoint: Wrapper;

  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const database = new rds.DatabaseInstanceFromSnapshot(this, 'Database', {
      snapshotIdentifier: 'snapshot-id'
      // ...more props here...
    });
    this.wrappedEndpoint = new Wrapper(this, 'Endpoint', database.dbInstanceEndpointAddress);
  }
}

interface StackBProps extends cdk.StackProps {
  wrappedEndpoint: Wrapper;
}
class StackB extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props: StackBProps) {
    super(scope, id, props);

    const fn = new lambda.Function(this, 'Fn', {
      // ...other props here...
      environment: {
        DATABASE_ENDPOINT: props.wrappedEndpoint.getValue(this),
      },
    });
  }
}

```

Now we are **able to update** the `snapshotIdentifier` prop in `StackA` (e.g. recover from snapshot after incident). There will be no downtime because `DatabaseInstanceFromSnapshot` are retained (orphaned).

Another solution here, since we are "transporting" an address, would have been to wrap it in a CNAME DNS record in a private hosted zone using Service Discovery...

**Comment by eladb** [comment]
This is a very interesting idea. I am transferring this to the RFC repo. Please follow the [RFC Repo README](https://github.com/aws/aws-cdk-rfcs/README.md) in order to submit this as an RFC.

**Comment by ambsw-technology** [comment]
@nakedible Are you talking about a hypothetical feature or the current behavior?  Doesn't the VPC ID output from `VpcStack` (required by `SubnetStack`) prevent `VpcStack` from updating?

**Comment by nija-at** [comment]
This can be implemented directly into the CDK's `core` module.

I've opened a PR implementing this here - https://github.com/aws/aws-cdk/pull/8891

**Comment by eladb** [comment]
@nija-at following up on your PR and my comment that adding this to `construct-compat` won’t work.

Can we add this as a feature of `Stack` (i.e in `StackProps`) ? Feels like the right place...

I am not sure it makes sense that _any_ scope will have that setting because it’s very specific to the relationship between stacks.

**Comment by nija-at** [comment]
@eladb - I suppose it implies that the user will configure this value?

While this does control relationship between stacks, this is dependent on the resource being referenced. 
It seems appropriate for the resource to mark itself as strong/weak. This also implies that not all resources exported from the same stack (and later imported) should be treated the same.

It might also be too late (hence, too painful) when the end user realizes that this property should be set. 
The realization will likely happen when the stack update for this resource fails. At this point, the user will have to move through a set of transitions to migrate their stacks from using `Fn::ImportValue` to SSM, because of the update/delete limitations that CloudFormation applies.

How about moving to a model where `Construct` in `constructs` contains an opaque key-value pair while `Construct` in the CDK is a stateless proxy/facade to it (not a subclass), and give it stronger typing?

**Comment by eladb** [comment]
@nija-at before we dive into the implementation, can we start by enumerating a few use cases and thinking what is the mental model of the user of this feature. Who should be able to make a decision about whether a reference is strong or weak?

It seems to me like this is something that users should be able to configure when they decide how to lay out their stacks (as oppose to being specified at the construct level and vended through a library).

I can see how it makes sense for some references to be defined as weak and some as strong, but I am wondering what would be reasonable ergonomics to be able to indicate at the stack level which references should be what.

**Comment by MrArnoldPalmer** [comment]
Some related issues for reference:
https://github.com/aws/aws-cdk/issues/1972
https://github.com/aws/aws-cdk/issues/22842

**Comment by JonWallsten** [comment]
As with https://github.com/aws/aws-cdk/issues/1972 we have created a LambdaLayer in `LambdaLayerStack` which is then passed as a reference (we use TypeScript) to `LambdaStack` where it's added as the `layers` prop in `NodejsFunction` for the functions.
The functions are then exported and in the `APIGatewayStack` for the `HttpLambdaIntegration`. 

The other use case is Lambda@Edge where we export the `experimental.EdgeFunction` from the `EdgeStack` and then import in the `CloudFrontStack` to be added as the `edgeLambdas` in `defaultBehavior`.

My simple understanding was that when you change and build a new EdgeFunction, the reference in the `Behavior` would just get the updated version and everything would be fine. The function should be deployed as a new version and the that version should be references here:

![image](https://github.com/aws/aws-cdk-rfcs/assets/5993909/0b9bdac5-11bf-4dfb-88df-b1b525ec2e20)


The same goes for layers. All the lambdas using the layer would just get the new version updated under `Layers`.

![image](https://github.com/aws/aws-cdk-rfcs/assets/5993909/3a358cfc-b3f3-48f9-8abe-e89ae2f7497e)

**Comment by m-radzikowski** [comment]
I'm interested in this, too.

In our case, we are using SSM parameters to pass references between stacks by default. We are aware that the relationships are not enforced this way, but we a) deploy all service stacks every time and b) refresh values in Lambda functions every few minutes anyway. Using SSM instead of CF outputs eliminates problems like mentioned above and also gives more flexibility when we want to delete stacks (on dev env) or quickly re-deploy the whole environment.

Right now, in CDK, in one stack we create SSM parameter, in other we read it with `StringParameter.valueForStringParameter()`, using a naming convention. Having CDK handle this and reference it by simple stack variables would be great.

**Comment by mrgrain** [comment]
Partially implemented by https://github.com/aws/aws-cdk/pull/22008

**Comment by evgenyka** [comment]
Won't fix. The feature drawbacks are too many to warrant the cost. Please see if https://github.com/aws/aws-cdk/pull/22008 covers the main use case.
