### ISSUE TITLE
Global Name Prefix

### ISSUE THREAD

**Issue by PeterBengtson** [aws/aws-cdk-rfcs#83]
### Description
I'm working as an expert AWS consultant with a large internet bank on a high-security project using CDK. It's the very first project at this bank using CDK, and it has allowed us to accelerate development considerably. However, when trying to prepare and deploy to the new staging and production accounts, we were suddenly faced with a problematic integration issue: the fact that boundary policies require us to prefix many resource names (such as lambdas, security groups, and many more) with the team name, e.g. `theTeam-my-lambda-function-72636364`.

The reason these prefix rules exist is due to the fact that there are some accounts shared by multiple teams. Imposing a network of rules keyed on name prefixes is the only way of keeping teams within one account separate, as tags can't be used for policy conditionals with all resources, e.g. lambdas. 

Shared accounts, while no longer best practice on AWS, do exist in many companies and will probably do so for quite some time, which means that our situation at this particular bank isn't unique. In order for CDK to gain widespread acceptance in brownfield situations, it would be good if there was an easy way – and above all a _standardised_ way – of specifying prefixes for CDK.

CDK doesn't support resource name prefixing out of the box. In fact, CDK follows best practices as established by CloudFormation and assumes full control of all generated names. Postprocessing the CloudFormation templates isn't an option, as tokens and other abstract features of CDK make simple text substitutions very difficult if not impossible.

Elad Ben-Israel proposed overloading the CDK method for generating logical names. While this would work, it's somewhat of a hackish solution in that it can be done in several different ways. The security powers-that-be at this bank would prefer a standardised solution in order to be able to recommend CDK.

### Proposed Solution

We propose a simple switch to the `cdk synth` command. It would be used as follows:
```
$ cdk synth --name-prefix='theTeam-'
```
This would add the prefix to all resource names, across all stacks. To provide even greater flexibility, the prefix could also be made part of the project configuration, obviating the need to type the proposed `--name-prefix` switch every time one synthesises the stacks.

### Environment

  - **CDK CLI Version:** 1.8
  - **OS:** all
  - **Language:** all

### Previously filed request
https://github.com/aws/aws-cdk/issues/3982

**Comment by eladb** [comment]
This is a very interesting idea. I am transferring this to the RFC repo. Please follow the [RFC Repo README](https://github.com/aws/aws-cdk-rfcs/README.md) in order to submit this as an RFC.

**Comment by nikita-sheremet-clearscale** [comment]
In my opinion, this is a critical feature. I have done a lot of projects with naming convention - it provides a lot of benefits: from defining access rights to ability to deploy simililar resources by different developers for testing.

**Comment by nikita-sheremet-clearscale** [comment]
My thoughts about prefixes

1. CDK adds stack id to the resource name. So when stack name is a bit long the final resource name will be truncated. When we deal with multiple lambdas (for example) a user able to distinguish lambda by just several symbols in the middle of name. Which is not well.
2. CDK staty with "policy" like "we add hash to resource name for easy replacing". But there is no distinction between stateful and stateless resources. Why do I need to add hash to lambda function name when it can be easily redeployed/recreated? A stack name is unique so lambdas will always have a unique prefix associated with the stack. So in total for stateless resources there is no need for hash at the end of name (or not for all of them at least).
3. If we have prefixes for all resources in the stack why we could not group all stacks into a single cloud application? Single prefix (always short) is easy for resource searching/looking without opening and investigation resource for tags, belonging to the CF stack etc. It is much easy and as it was mentioned better for security because I can limit all lambdas access (for example) with name prefix and all bucket with prefix - because all of them belongs to same cloud applciation.
4. About stateless resources. Consider example of Glue data catalog. When I deploy a database - it is global for region in account. So when I deploy same database and different stack (scope) name I will go en error because I have to manual change the name. Using prefixing allow me to deploy same CDK application with different name and I got different database name. Like `dev_database` and `prod_database`. Pleae not that changing database name is much easer then autogenerated table naems. Here we got interesting situation when stateless resources have a hash while they can be easy redeployed but stateful do not have any prefix for resource separation and have to be manual managed.
5. If use hashing is so good and prefixing is bad. Why do CDK team added qualifier for CDK bootstrap? Looks like prefixing is better for application managing, is not it? >:-) Seriously, bootstrapping is a good example when developer have to deal with multiple stacks/resources tied together and this example shows usthat prefixing must be added into cdk.

About prefix requirements - it should be short (4-5 symbols) and contains letters only because different was resources support (or not) different symbols like dash, lodash etc.

**Comment by nikita-sheremet-clearscale** [comment]
The code
```
export class BaseStack extends Stack {
  public allocateLogicalId(element: CfnElement) {
    const orig = super.allocateLogicalId(element);
    const prefix = this.node.tryGetContext('prefix');
    return prefix ? prefix + orig : orig;
   }
}
```

Does not always work as expected because it adds a prefix twice.

Consdier the following:

```
public class PrefixedStack extends Stack {
  public PrefixedStack(
      App scope,
      String id,
      StackProps props
    ) {
    super(scope, prefix(scope, id), props);
  }

  private static String prefix(App scope, String id) {
    var prefix = scope.getNode().tryGetContext("app.prefix").toString();
    return String.join(
        "-",
        prefix,
        id
    );
  }
}
```

This adds a prefix to Stack, then every resource (like lambda) which has a stack name prefix automatically has a prefix. But even with this, it is better to pass prefixed name directly because some resources like State machine does not have stack name and it is unclear how to fix this.

**Comment by awsmjs** [comment]
Closing this ticket as it has gone stale and does not reflect current priorities. We suggest to pursue experimentation in a separate package or a fork if needed.
