### ISSUE TITLE
Master developer guide sources in main repo

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk-rfcs#9]
|PR|Champion|
|--|--------|
|# |        |

## Description

CloudFormation released[ resource import](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resource-import-supported-resources.html
)
How should we support it in the CDK?

## Progress

- [x] Tracking Issue Created
- [ ] RFC PR Created 
- [ ] Core Team Member Assigned 
- [ ] Initial Approval / Final Comment Period
- [ ] Ready For Implementation
    
    - [ ] implementation issue 1
- [ ] Resolved

**Comment by mrgrain** [comment]
Title doesn't match description 🤷🏻 

Marking this RFCs as `stale` since there has been little recent activity and it is not currently close to getting accepted as-is. We appreciate the effort that has gone into this proposal. Marking an RFCs as stale is not a one-way door. If you have made substantial changes to the proposal, please open a new issue/RFC. You might also consider raising a PR to [aws/aws-cdk](https://github.com/aws/aws-cdk/) directly or self-publishing to Construct Hub.
